name: deploy to ghpages
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: master
    steps:
      - uses: actions/checkout@v3
      - uses: actions/configure-pages@v1
        id: pages
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: npm install and build
        run: |
          npm ci
          npm run build --if-present
        env:
          CI: true
      - name: deploy
        run: npm run deploy
