name: deploy to ghpages
on:
  push:
    branches:
      - master
jobs:
  deploy_source:
    name: build and deploy to ghpages
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: npm run build
      - name: deploy
        run: npm run deploy
